# Ctrl+a를 prefix로 (Screen 사용자들에게 친숙)
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# vi 모드 사용
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
set -g extended-keys on
set -g extended-keys-format csi-u
set -g assume-paste-time 0

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins'

# TPM 플러그인 목록 (prefix + I can install plugins)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-pain-control'

# set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'sainnhe/tmux-fzf'

set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'mocha'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# 반드시 마지막 줄에
run '~/.config/tmux/plugins/tpm/tpm'
